version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ main port
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf  # Mount the custom config file
    networks:
      - app_network
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 5

  mongodb:
    image: "mongo"
    container_name: mongodb
    ports:
      - "27017:27017" # MongoDB default port
    networks:
      - app_network
    volumes:
      - mongo_data:/data/db

  fastapi:
    build: ./fastapi
    container_name: fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env # Ensure that the .env file is being passed
    networks:
      - app_network
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started

  database_subscriber:
    build: ./database_subscriber
    container_name: db_subscriber
    env_file:
      - .env # Ensure that the .env file is being passed
    networks:
      - app_network
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
