version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ main port
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      - app_network

  mongodb:
    image: "mongo"
    container_name: mongodb
    ports:
      - "27017:27017" # MongoDB default port
    networks:
      - app_network
    volumes:
      - mongo_data:/data/db

  fastapi:
    build: ./fastapi
    container_name: fastapi
    ports:
      - "8000:8000" # FastAPI exposed port
    networks:
      - app_network
    depends_on:
      - rabbitmq
      - mongodb

  database_subscriber:
    build: ./database_subscriber
    container_name: db_subscriber
    networks:
      - app_network
    depends_on:
      - rabbitmq
      - mongodb

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
